### ISSUE TITLE
Nach Umstellung auf App MyKobold funktioniert die Anmeldung nicht mehr

### ISSUE THREAD

**Issue by RK62** [Eisbaeeer/ioBroker.vr200#13]
Scheinbar hat Vorwerk das Anmeldeverfahren geändert: Nach dem Umstieg auf die App _MyKobold_ sind die ursprünglichen Anmeldedaten nicht mehr gültig und dieser Adapter lässt sich nicht mehr nutzen. Ab 01.03.2021 ist nur noch das neue Verfahren gültig.

Gruß, Ralf

**Comment by GRaptor** [comment]
Ja, kann ich bestätigen.
Die Anmeldedaten selbst sind (bei mir) die gleichen. Aber nach Umstieg auf MyKobold  funktioniert die alte App nicht mehr und damit auch der Adapter nicht.

**Comment by mhoster83** [comment]
Same here

**Comment by aski71** [comment]
Same here.
Wird dieser Adapter überhaupt noch gepflegt?

**Comment by Eisbaeeer** [comment]
> Same here.
> Wird dieser Adapter überhaupt noch gepflegt?

Hallo. Ja der Adapter wird noch gepflegt. Du kannst dich aber auch gerne beteiligen ;-)
https://forum.iobroker.net/topic/11337/announce-vorwerk-vr200-saugroboter-adapter/71

**Comment by aski71** [comment]
Hi,
würde ich sogar, wenn ich das könnte. 😊 Hatte mich nur gewundert, weil es mir so vorkam, als sei die letzte Version schon Jahre alt. 
Nix für ungut und danke für dir hatte Arbeit. 👍

**Comment by LenkerIsNotACoder** [comment]
Hi,

nicoh88 hat sein Node-Modul vor knapp 3 Wochen von 0.1.3 auf 0.2.0 aktualisiert (https://github.com/nicoh88/node-kobold). Ich habe testhalber die package.json einfach auf folgendes angepasst (Zeile 41)
` "node-kobold": "^0.2.0"`
und anschließend via `npm update` das aktualisierte Modul installiert.

In der Readme von node-kobold gibt es 2 curl-Befehle, wie man an die im folgenden notwendige ID kommt. Einfach ausführen und dann in der main.js des vr200-Moduls folgende Zeile einfügen (Zeile 289, vor client.authorize):
`client.setToken("ID_AUS_CURL_KOMMANDOS"`

In den Adapter-Einstellungen ist das Passwort nun vollkommen egal, die Mail-Adresse muss aber mit der in den beiden curl-Befehlen verwendetebn übereinstimmen.

Ich weiß, dass das mehr als dreckig ist, aber ich habe zu wenig Ahnung von NodeJS Entwicklung (oder Entwicklung generell), um einen vernünftigen Pull-Request zu erstellen. Vielleicht hilft die Beschreibung hier ja wenigstens ein bisschen weiter.

**Comment by LenkerIsNotACoder** [comment]
Noch eine kleine Erweiterung, die mir gerade ein- und auffiel:
Anstatt wie von mir beschrieben die ID direkt in die main.js zu schreiben, habe ich sie jetzt ins Passwort-Feld eingefügt und die setToken funktion geändert:
`client.setToken(password);`

Damit gibt es noch weniger Code-Änderungen.

**Comment by praenti** [comment]
Ich hab mal einen PullRequest angelegt mit Änderungen, damit der Adapter mit dem neuen Auth-Verfahren funktioniert. Probierts mal aus ;-).

**Comment by RK62** [comment]
> Ich hab mal einen PullRequest angelegt mit Änderungen, damit der Adapter mit dem neuen Auth-Verfahren funktioniert. Probierts mal aus ;-).

Für einen "ioBroker Normalo-User": 
Was bedeutet das? 
Wie kann ich die Anpassung aktivieren?

Danke, Ralf

**Comment by fiesch** [comment]
@RK62 - wurde bereits vor 12 tagen in den master branch gemerged - also einfach per GitHub Link installieren (GutHub Symbol und dann am einfachsten auf "Beliebig" tag und die URL https://github.com/Eisbaeeer/ioBroker.vr200 eintragen

**Comment by fiesch** [comment]
@praenti / @Eisbaeeer  - Danke für den PR / merge - kann bestätigen dass das beim Schwiegervater jetzt tut.. 
AAAllerdings - das ist ja OAuth2 / OIDC - mit dem Access token flow. Gibt es denn eine Logik das Token aktuell zu halten? 
(also per Refresh Token ein neues Access Token zu holen regelmäßig) - sonst läuft das Token aus den CURL commands irgendwann aus und man darf das selbe Spielchen nochmal machen

**Comment by heymkeyu** [comment]
> sonst läuft das Token aus den CURL commands irgendwann aus und man darf das selbe Spielchen nochmal machen
Wie lange hält denn das Token etwa? Ich bin aufgrund dieses Themas noch etwas zurückhaltend mit dem Update der Firmware und des Adapters - aber irgendwann ist ja Schluss mit der Karenzzeit...

**Comment by praenti** [comment]
Hi,

sorry dass ich mich erst jetzt melde. Soweit ich das sehen kann hält das Token seit ich damals die Änderung gemacht hab, allerdings weiß ich auch nicht, wann das Token abläuft.
Ich hoffe mal dass Vorwerk den Token in der API etwas länger valide hält. Mit CURL alleine lässts sich ja nicht lösen. Da müsste man die Mail von Vorwerk ja auch parsen um den Code zu bekommen. Irgendwie ist die neue API da leider aufwändig zu automatisieren.

**Comment by Eisbaeeer** [comment]
Ich habe an anderer Stelle ähnliche Probleme. Eine Möglichkeit wäre, einen oAuth2 Proxy zu bauen. Dieser aktualisiert dann die Token automatisch bzw. Regelmäßig. Ich bin aber immer noch sehr busy. Grüße Lars

**Comment by fiesch** [comment]
> > sonst läuft das Token aus den CURL commands irgendwann aus und man darf das selbe Spielchen nochmal machen
> 
> Wie lange hält denn das Token etwa? Ich bin aufgrund dieses Themas noch etwas zurückhaltend mit dem Update der Firmware und des Adapters - aber irgendwann ist ja Schluss mit der Karenzzeit...

DIe token lifetime steht in der Ausgabe des 2ten CURL Kommandos.. habs jetzt leider grade nicht mehr da

**Comment by fiesch** [comment]
> > > sonst läuft das Token aus den CURL commands irgendwann aus und man darf das selbe Spielchen nochmal machen
> > 
> > 
> > Wie lange hält denn das Token etwa? Ich bin aufgrund dieses Themas noch etwas zurückhaltend mit dem Update der Firmware und des Adapters - aber irgendwann ist ja Schluss mit der Karenzzeit...
> 
> DIe token lifetime steht in der Ausgabe des 2ten CURL Kommandos.. habs jetzt leider grade nicht mehr da

OK könnt ihr ignorieren, war noch nicht ganz wach - das "expires_in" der CURL Antwort bezieht sich auf das access token das nur gegenüber auth0.com relevant ist.

Für die API bei Vorwerk geht es aber um das ID Token.. das ist ein JWT und lässt sich z.B. auf https://jwt.io/  decoden.. hier drin hats ein eigenes "exp" Feld dass die Gültigkeit des ID Tokens angibt..

Das wiederum ist wirklich unstressig - denn bei mir läuft das- wenn man es jetzt frisch abruft - am 19ten Januar 2089 ab.. das sollte für die meisten Anwendungsfälle reichen :)

**Comment by heymkeyu** [comment]
> Das wiederum ist wirklich unstressig - denn bei mir läuft das- wenn man es jetzt frisch abruft - am 19ten Januar 2089 ab.. das sollte für die meisten Anwendungsfälle reichen :)

Super, Danke Matthias für die Info! :-) 👍

**Comment by ihavenonick** [comment]
Viel Bahnhof für mich gerade, deshalb ne kurze Frage dazu.
Läuft der Adapter nun bei der Umstellung auf die neue APP?

**Comment by RK62** [comment]
> Viel Bahnhof für mich gerade, deshalb ne kurze Frage dazu.
> Läuft der Adapter nun bei der Umstellung auf die neue APP?

Bei mir hat‘s funktioniert und ich schliesse dieses Issue:
- Adapter aus github über den vorhandenen Adapter installieren (github-Symbol auf Adapterseite)
- Dann dem Link auf der Config-Seite folgen und einen Token erzeugen. Dabei die eMail-Adresse aus der Anmeldung an der neuen App verwenden
- Generierten Token einsetzen, dieser wird dann an Stelle der alten Anmeldung genutzt

Danke für die Arbeit!

Gruß, Ralf

**Comment by philbamberg** [comment]
Ich weiß nicht, ob ich zu dämlich bin, aber ich habe die geforderten Angaben in der Anfrage des tokens gemacht und ihn auch rauskopiert (es handelt sich schon um den elend langen Code, der angezeigt wird oder?). Nach neustart des Adapters steht im Log "_vr200.0 | 2021-01-02 10:39:11.463 | warn | (29558) no robots found_" was mache ich falsch? Ich habe schon, da ich dachte ich wäre zu doof, mit einem anderem Handy die App installiert und mich mit der selben Emailadresse angemeldet. Dort hats funktioniert.
