### ISSUE TITLE
API Token

### ISSUE THREAD

**Issue by FlexerJR** [Eisbaeeer/ioBroker.vr200#16]
Hallo Eisbaeeer, 

ich habe mir die aktuellste Version von git gezogen da der VR300 damit kompatibel sein soll. Jetzt stehe ich aber vor dem Problem mit dem API Token. 

Leider sind meine Kenntnisse nur auf Blockly beschränkt. Ein fertiges Javascript bekomme ich gestartet. 

Den Link habe ich mir angeschaut jedoch werde ich nicht drauf schlau.

Viele Grüße

**Comment by Eisbaeeer** [comment]
Habe eben gesehen, dass du das Forum gefunden hast und das Problem behoben ist.
