### ISSUE TITLE
goToBase

### ISSUE THREAD

**Issue by ihavenonick** [Eisbaeeer/ioBroker.vr200#3]
goToBase funktioniert nicht. Wird der DP auf true gesetzt, springt er sofort wieder auf fals und der VR200 bleibt da wo er ist. FW ist derzeit 2.1.4.

**Comment by Eisbaeeer** [comment]
Bitte folgendes beachten, siehe README.MD:
return to base
status.dockHasBeenSeen has to be true
VR200 has to be in paused or stopped state (commands.stop / commands.pause)
set commands.goToBase to true

**Comment by ihavenonick** [comment]
OK danke, wer lesen kann hat klare Vorteile ;-)

**Comment by RalphZink** [comment]
Hallo,
ich bräuchte mal Hilfe, habe genau das selbe Problem wie mein Vorgänger.
alles funktioniert außer goToBase nicht, ich stoppe den Saugroboter der Status status.dockHasBeenSeen bleibt auf false wie kann ich den Status auf true setzen?

Vielen Dank im Voraus
