### ISSUE TITLE
DP mit Uhrzeit/Datum letzte Reinigung möglich?

### ISSUE THREAD

**Issue by ihavenonick** [Eisbaeeer/ioBroker.vr200#4]
Wie die Überschrift schon erahnen lässt, würde mir ein DP, der das Datum und oder Uhrzeit der letzten Reinigung beinhaltet weiterhelfen. Alternativ auch ein DP der die vergangene Zeit seit der letzten Reinigung anzeigt.
Klar könnte ich mir da auch was selber basteln, nur wenn's möglich wäre, wäre das eben einfacher :-)

**Comment by Eisbaeeer** [comment]
Hallo
Das kannst du doch über den Zeitstempel des Datenpunktes abfragen. Die Zeit seit der letzten Reinigung ist dann ebenso darstellbar. Widget - (basic - Last change  Timestamp) und dann Status auswählen. 
Gruß Eisbaeeer
