### ISSUE TITLE
goToBase

### ISSUE THREAD

**Issue by RalphZink** [Eisbaeeer/ioBroker.vr200#5]
Hallo,
ich bräuchte mal Hilfe, habe ein Problem mit goToBase, alles funktioniert außer goToBase nicht, ich stoppe den Saugroboter der Status status.dockHasBeenSeen bleibt aber auf false wie kann ich den Status auf true setzen? ich bin ein blutiger Anfänger, wäre schon wenn du mir das ausführlich beschreiben könntest.
Vielen Dank im Voraus

**Comment by Eisbaeeer** [comment]
Hallo Ralph
Also das ist so. Du kannst den Status dockHasBeenSeen gar nicht auf true setzen. Das macht der VR200 wenn er dann die Basis mal gesehen hat. Bei mir dauert das meist eine Weile bis der Status gesetzt ist bzw. bis der VR200 mal die Basis entdeckt hat. Soll heißen, dass er ne ganze Weile vor der Basis saugen kann, der Status aber trotzdem auf false bleibt. Wenn du also gleich nach dem Starten des VR200 wieder stoppst, kannst du ihn nicht zur Basis zurückschicken. Das ist übrigens das gleiche Verhalten, wenn du ihn mit der Fernbedienung startest.
Du musst also immer erst den Status prüfen (was kann der VR200 aktuell ausführen), sonst bringt der Steuerbefehl nichts. Wenn also der Status nicht auf canStart = true ist, kannst du ihn auch nicht starten.
Hoffe das war verständlich erklärt. Übrigens verhält sich z.B. die Eco Funktion auch sehr störrisch. Nur wenn der VR200 auf stop steht, dann die Eco Funktion auf true steht und dann gestartet wird, saugt er auch in Eco. Während er schon gestartet wurde, kann die Eco Funktion nicht umgeschaltet werden. Das geht aber wohl mit der Fernbedienung. Leider ist da die Schnittstelle zum VR200 nicht so flexibel.
