### ISSUE TITLE
VR300

### ISSUE THREAD

**Issue by FlexerJR** [Eisbaeeer/ioBroker.vr200#9]
Ist der Adapter auch in der Lage den VR300 zu steuern? Genial wäre eine Steuerung analog zur VR Kobold App mit Grundriss in Vis. Selektive Steuerung, für nur Küche. NoGo Lines usw. 

Viele Grüße

**Comment by Eisbaeeer** [comment]
Hallo. In der aktuellen Version wird der VR300 nun unterstützt. Die erweiterten Funktionen sind derzeit aber noch nicht implementiert. Grundlegen eben nur diese, die der VR200 auch kann.

**Comment by crusader85** [comment]
Hallo Eisbaeeer, 
magst du die VR300-Funktionen noch einbauen? Ich würde mich auch gerne als Tester anbieten. Die Raumansteuerung wäre echt praktisch. 

Viele Grüße
